"""empty message

Revision ID: 187bd5a5f574
Revises: ac6e8347d27e
Create Date: 2024-05-24 15:22:22.646249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187bd5a5f574'
down_revision = 'ac6e8347d27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
