"""user: add lastlogin

Revision ID: 622bb0703332
Revises: f7cb544a4cb1
Create Date: 2023-04-28 05:20:03.578871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622bb0703332'
down_revision = 'f7cb544a4cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
